spring:
  datasource:
    url: jdbc:tc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:liquibase/db.changelog.xml
    contexts: test
    drop-first: true

uri:
  wallet:
    scheme: http
    host: localhost:7000
    resource-path: 'wallets'
    timeout: 3000

aws:
  sns:
    region: us-east-1
    endpoint: http://localhost:4566
    topic-arns:
      persons: arn:aws:sns:us-east-1:000000000000:persons-sns-topic